@isTest
public class ErrorLogHandlerController_Test {
    static testMethod void ErrorLogHandlerController_TestMethod()
    {/*
        Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234');
        insert acc;
        
        Contact con = TestData.createContact('1234');
        insert con;
        
        CalypsoData__c cdTestWID = TestData.createCalypsoData('1245', null, acc.Id);
        insert cdTestWID;
        
        ErrorLogHandlerController errorObj = new ErrorLogHandlerController();
        errorObj.actionFilter();
        CalypsoData__c cdTestWIDs = [SELECT CD_TradeDate__c FROM CalypsoData__c WHERE CD_TradeID__c ='111888'];
        System.debug('Trade Date>>>>'+cdTestWIDs.CD_TradeDate__c);
        System.assertEquals(system.today(), cdTestWIDs.CD_TradeDate__c);
        
        //ErrorLogHandlerController.wrapAccount errorWrapObj = new ErrorLogHandlerController.wrapAccount();
    */}
}