/*
@Author        : Krishna
@Name          : ReportRepOppty_Sched
@Created Date  : 20th May 2019
@Description   : This is a Schedule class for ReportRepOppty_Batch Class
@version       : 1.0
*/
global class ReportRepOppty_Sched implements Schedulable {
/**
* @description       Method to Schedule a ReportRepOppty_Batch ClassBatch class 
* @name              execute
* @param             SchedulableContext
* @return            Void
* @throws            NA
*/ 
    global void execute(SchedulableContext ctx) {
        //ReportRepOppty_Batch obj = new ReportRepOppty_Batch();
        //Database.executeBatch(obj,500);
    }
    
}